//HOLIDAY ROUTES
/////////////////////////////////////////////////////// WEEK 5

//*****************LOCAL***************** 

### Local app GET holiday records
GET http://localhost:8000/holiday

### Local app GET holiday specific holiday record
GET http://localhost:8000/holiday/63446f7d2d0e51f7cfa00cb2

### Local app POST holiday records
POST http://localhost:8000/holiday
Content-Type: application/json

{
  "name": "any",
  "occurence": "any",
  "group": "any"
}
//*****************PRODUCTION***************** 

###  App through render GET holiday records
GET https://custody-api.onrender.com/holiday

###  App through render GET specific holiday record
GET https://custody-api.onrender.com/holiday/63446f7d2d0e51f7cfa00cb2

###  App through render POST holiday records
POST https://custody-api.onrender.com/holiday
Content-Type: application/json

{
  "name": "any",
  "occurence": "any",
  "group": "any"
}

/////////////////////////////////////////////////////// WEEK 6


### Local app PUT holiday specific holiday record
PUT http://localhost:8000/holiday/6344a66b8ed28722af092910
Content-Type: application/json

{
  "name": "TEST3"
}

### Local app DELETE holiday specific holiday record
DELETE  http://localhost:8000/holiday/634e2453ad2596c339173568
